print("[ZZTestMod] Loaded - idle (no active probes).\n")

-- Research scratchpad only. Feature code lives in MoreLoadoutSlots/,
-- LoadoutNamer/, EquipmentSearch/, and InventoryTracker/ (each
-- <Mod>/Scripts/main.lua).
--
-- IDLE. Last campaign: can InventoryTracker's wiki links be made genuinely
-- clickable (2026-07-30), 4 rounds, concluded - findings recorded in
-- docs/remnant2-modding-research.md 3.18. Summary:
--   - RegisterHook is a genuinely different mechanism from delegate binding
--     (doesn't touch MulticastInlineDelegateProperty at all - confirmed via
--     UE4SS docs and a public precedent hooking a base UMG engine class),
--     but click detection via it turned out to be a dead end anyway: a
--     RegisterHook("/Script/UMG.UserWidget:OnMouseButtonDown", ...) hook
--     registered with no error but never fired once, across three distinct
--     target types (our own bare-constructed nested-UserWidget wrapper,
--     real interactive menu buttons, and blank non-interactive menu
--     background) - treated as exhausted rather than a guess away from
--     working.
--   - class:ForEachFunction(callback) safely enumerates every real
--     UFunction on a class/struct (callback gets the UFunction; use
--     fn:GetFName():ToString() for its name) - use this instead of
--     guessing function names for RegisterHook targets. Found mouse
--     events (OnMouseButtonDown etc) exist ONLY on UserWidget, not on
--     Widget or individual leaf widgets like TextBlock.
--   - UKismetSystemLibrary::LaunchURL(FString) DOES work - found via
--     StaticFindObject("/Script/Engine.Default__KismetSystemLibrary"),
--     called as ksl:LaunchURL(url) with a plain Lua string. User-confirmed:
--     opens a real browser tab. This half of "clickable link" is solved
--     and reusable by any trigger mechanism, including the keyboard-driven
--     row-selection fallback (TODO.md) that this campaign's conclusion
--     points back to.
--
-- Older diagnostics (loadout probes, input logger, delegate Add() test,
-- chain tracers, EquipmentSearch P1-P8, InventoryTracker trait ownership
-- probes, InventoryTracker UI-construction rounds) are all recoverable
-- from git history.
