print("[ZZTestMod] Loaded - idle (no active probes).\n")

-- Research scratchpad only. Feature code lives in MoreLoadoutSlots/,
-- LoadoutNamer/, and EquipmentSearch/ (each <Mod>/Scripts/main.lua).
--
-- IDLE. Last campaign: Collection Tracker (new mod #4 idea) Phase 0 research
-- spike (2026-07-27), rounds 1-5, all concluded; findings recorded in
-- docs/remnant2-modding-research.md 3.10. Summary of what they proved:
--   - No persistent "ever obtained" flag exists anywhere in native reflection
--     (grepped the full /Script/Remnant CXX header dump for Discover/Journal/
--     Codex/Compendium - zero matches). Tracking can only ever reflect
--     CURRENT inventory contents, same ceiling as EquipmentSearch.
--   - FindAllOf-sourced live component instances support IsValid/GetFullName/
--     GetOuter/GetClass/direct named-field indexing, but NOT ForEachProperty/
--     GetFunction (both error "TrivialObject value"). StaticFindObject-
--     sourced STRUCT objects (not live components) do support ForEachProperty
--     (EquipmentSearch's InspectInfo pattern) - a different code path.
--   - UE4SS's "Dump CXX Headers" dumper (Dumpers tab, F10/Tilde debug GUI)
--     gives real typed native function signatures - reach for this earlier
--     next time instead of guessing via trial calls.
--   - HAZARD (native crash, pcall useless): RemnantPlayerInventoryComponent's
--     HasItem(TSoftClassPtr<AItem> ItemBP, int32 Quantity, int32 ItemLevel)
--     crashed the game when called with a raw UClass value for ItemBP.
--     TSoftClassPtr is a STRUCT (wraps FSoftObjectPath), not a raw pointer
--     like TSubclassOf - same class of mistake as unwrapped FText (3.4b).
--     Do not call this (or anything else taking TSoftClassPtr) without first
--     working out the correct Lua-side soft-pointer construction.
--   - Superseding approach: RemnantPlayerInventoryComponent.Items (a plain
--     TArray<FInventoryItem> property) reads directly with zero risk - no
--     function call needed. Ownership checks should scan this array's
--     .ItemBP entries instead of calling HasItem.
--
-- Older diagnostics (loadout probes, input logger, delegate Add() test, chain
-- tracers, EquipmentSearch P1-P8) are all recoverable from git history.
