print("[ZZTestMod] Loaded - idle (no active probes).\n")

-- Research scratchpad only. Feature code lives in MoreLoadoutSlots/,
-- LoadoutNamer/, and EquipmentSearch/ (each <Mod>/Scripts/main.lua).
--
-- IDLE. Last campaign: EquipmentSearch probe rounds P1-P8 (2026-07), all
-- concluded; findings recorded in docs/remnant2-modding-research.md 3.6b.
-- Summary of what they proved:
--   P1 (F2): unhiding Widget_InventorySearchFilter_C + SearchFilterText works;
--       the CanSeeSearchBar gate binding is inert after construction.
--   P4 (F3): card:Get_InspectInfo({}) out-param spreading works; ItemID is a
--       plain readable property on Widget_InventoryItem_C.
--   P5 (F4): HAZARD - UE4SS zero-fills synthesized struct params; ToString()
--       on a zero-filled FText is a native crash pcall cannot catch. Passing a
--       REAL info struct into ModifyInspectInfo doesn't crash but changes
--       nothing -> re-invoking the game's inspect pipeline is a dead end.
--   P6 (F5): HAZARD - ForEachProperty does NOT walk super-structs; InspectStat
--       inherits InspectStatBase (Label, CustomDescription, ...). Walk
--       GetSuperStruct() or field lists are silently incomplete. Also:
--       Widget_ItemTooltip_C:GetInspectInfo hook never fires on hover.
--   P7 (F6): trigger-ring effect text lives in Stats[].CustomDescription
--       (inherited field); stat-ring effect text in Mods[].Label.
--   P8 (F7): reading CustomDescription on Stats entries is safe for all 213
--       rings -> the earlier full-sweep crash was reading a Stats-only field
--       on Mods entries (structs differ per array; per-array field lists fix).
--
-- Older diagnostics (loadout probes, input logger, delegate Add() test, chain
-- tracers) are all recoverable from git history.
