"""Regenerate InventoryTracker/Scripts/master_list_data.lua from
dev-data/master_list/*.json.

Writes a standalone `return { ... }` data file - no JSON library needed at
runtime (UE4SS's Lua API doesn't bundle one) and no custom parser to write
and ship in the mod. main.lua loads it with `require("master_list_data")`,
standard practice for splitting a UE4SS Lua mod across multiple files.

Always a full file overwrite, never a partial edit - there's nothing else in
this file to accidentally clip. Always writes UTF-8 with no BOM -
PowerShell's default utf8 encoding once silently added a BOM here that broke
Lua's parser ("unexpected symbol near '<\\239>'", 2026-07-27, research doc
3.12); Python's Path.write_text(encoding="utf-8") never does that.

Run the match_*.py scripts first to refresh dev-data/master_list/*.json,
then run this.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MASTER_LIST_DIR = ROOT / "dev-data" / "master_list"
DATA_PATH = ROOT / "InventoryTracker" / "Scripts" / "master_list_data.lua"


def lua_escape(s: str) -> str:
    return s.replace('"', '\\"')


def main():
    entries = []
    for f in sorted(MASTER_LIST_DIR.glob("*.json")):
        if f.stem.endswith("_unmatched"):
            continue
        data = json.loads(f.read_text(encoding="utf-8"))
        if not isinstance(data, list) or not all(isinstance(e, dict) and "category" in e for e in data):
            raise SystemExit(
                f"{f.relative_to(ROOT)} doesn't look like a master-list file "
                f"(expected a list of {{category, name, classPath}} objects) - "
                f"dev-data/master_list/ must only contain category output files, "
                f"put diagnostic/report files elsewhere."
            )
        entries.extend(data)
    entries.sort(key=lambda e: (e["category"], e["name"]))

    lines = [
        "-- Generated by scripts/InventoryTracker/generate_lua.py - do not hand-edit.",
        "-- Source data: dev-data/master_list/*.json (rebuilt by the match_*.py scripts).",
        "return {",
    ]
    for e in entries:
        fields = [
            f'category = "{lua_escape(e["category"])}"',
            f'name = "{lua_escape(e["name"])}"',
            f'classPath = "{lua_escape(e["classPath"])}"',
        ]
        # Any other string-valued key (e.g. traits' "source") rides along
        # generically - keeps this script reusable without a schema bump
        # every time a category needs one extra display field.
        for key, value in e.items():
            if key in ("category", "name", "classPath"):
                continue
            if isinstance(value, str) and value:
                fields.append(f'{key} = "{lua_escape(value)}"')
        lines.append("    { " + ", ".join(fields) + " },")
    lines.append("}")
    lines.append("")

    DATA_PATH.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"Wrote {len(entries)} entries to {DATA_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
