print("[InventoryTracker] Loaded and running.\n")

-- InventoryTracker: shows which unique equippable items the player currently
-- has vs. what's missing, in a real in-game panel (F8 to toggle, Page Up/
-- Page Down to switch category while it's open).
--
-- CONFIRMED CEILING (research doc 3.10): the game has no persistent "ever
-- obtained" flag anywhere in native reflection. This mod can only ever
-- reflect CURRENT inventory contents - a sold/dismantled unique will show as
-- missing again. Known, accepted limitation, not a bug.
--
-- Ownership check: scan RemnantPlayerInventoryComponent.Items (a plain
-- TArray<FInventoryItem> property, read directly - no function call) for an
-- entry whose .ItemBP class path matches the master list entry. Deliberately
-- NOT calling HasItem() - it takes a TSoftClassPtr (a struct, not a raw
-- pointer) and crashed the game when called with a raw UClass value
-- (research doc 3.10 hazard). Property reads only, per the risk ladder.
-- Traits use a different check entirely (readTraitLevels below) - see
-- research doc 3.16.
--
-- MASTER LIST: 699 entries across rings/amulets/armor/weapons/mods/mutators/
-- engrams/unlockable traits, built by scripts/InventoryTracker/*.py (see
-- that folder and research doc 3.11-3.16 for the full build pipeline).
-- Data lives in master_list_data.lua, generated by generate_lua.py - not
-- hand-maintained here. To add a category or fix a name, edit the Python
-- pipeline and re-run it, don't hand-edit master_list_data.lua.
--
-- UI: a bare-Lua-constructed UMG panel (no existing Blueprint template
-- asset needed) - full construction recipe, and the two non-obvious traps
-- that shaped this code (AddToViewport's own slot never being writable;
-- SetInputMode needing WidgetBlueprintLibrary's Ex-suffixed wrapper since
-- the raw API isn't reflected at all), are in research doc 3.17. Clickable
-- tabs/links are NOT possible from pure Lua (UE4SS can't bind
-- MulticastInlineDelegateProperty) - category switching is keybind-driven
-- instead, and wiki links are shown as plain readable text. Full vision
-- (tabs, clickable links) deferred to a future Blueprint-modding pass -
-- see TODO.md at the repo root.
local MASTER_LIST = require("master_list_data")

local CATEGORY_ORDER = { "Ring", "Amulet", "Armor", "Weapon", "Mod", "Mutator", "Engram", "Trait" }

local function groupByCategory(list)
    local grouped = {}
    for _, cat in ipairs(CATEGORY_ORDER) do grouped[cat] = {} end
    for _, item in ipairs(list) do
        if grouped[item.category] then
            table.insert(grouped[item.category], item)
        end
    end
    return grouped
end
local MASTER_LIST_BY_CATEGORY = groupByCategory(MASTER_LIST)

local function findOwnedInventoryComponent(pawn)
    local all = FindAllOf("RemnantPlayerInventoryComponent")
    if not all then return nil end
    for _, c in ipairs(all) do
        local ok, owner = pcall(function() return c:GetOuter() end)
        if ok and owner then
            local okSame, same = pcall(function() return owner:GetFullName() == pawn:GetFullName() end)
            if okSame and same then return c end
        end
    end
    return nil
end

-- Returns a set of owned class-path strings (lowercased) read from the live
-- Items array. Built fresh each check - session-lifetime caching can come
-- later once this is proven correct.
local function readOwnedClassPaths(inv)
    local owned = {}
    local okItems, items = pcall(function() return inv.Items end)
    if not okItems or items == nil then
        print("[InventoryTracker] readOwnedClassPaths: inv.Items unreadable.\n")
        return owned
    end
    local okLen, len = pcall(function() return #items end)
    if not okLen then
        print("[InventoryTracker] readOwnedClassPaths: #items unreadable.\n")
        return owned
    end
    for i = 1, len do
        local okEntry, entry = pcall(function() return items[i] end)
        if okEntry and entry ~= nil then
            local unwrapped = entry
            if type(entry) == "userdata" then
                local okGet, inner = pcall(function() return entry:get() end)
                if okGet and inner ~= nil then unwrapped = inner end
            end
            local okClass, itemClass = pcall(function() return unwrapped.ItemBP end)
            if okClass and itemClass ~= nil then
                local okPath, path = pcall(function() return itemClass:GetFullName() end)
                if okPath and path then
                    -- GetFullName() looks like "BlueprintGeneratedClass /Game/.../Ring_X.Ring_X_C";
                    -- keep just the "/Game/..." part to compare against MASTER_LIST classPath.
                    local assetPath = string.match(path, "(/Game/.+)$")
                    if assetPath then owned[string.lower(assetPath)] = true end
                end
            end
        end
    end
    return owned
end

local function findTraitsComponent(pawn)
    local all = FindAllOf("TraitsComponent")
    if not all then return nil end
    for _, c in ipairs(all) do
        local ok, owner = pcall(function() return c:GetOuter() end)
        if ok and owner then
            local okSame, same = pcall(function() return owner:GetFullName() == pawn:GetFullName() end)
            if okSame and same then return c end
        end
    end
    return nil
end

-- Traits work differently from every other category: ownership isn't an
-- inventory scan, it's presence in TraitsComponent.Traits (a plain
-- TArray<FTraitInfo> property - Level is the player's allocated points,
-- 0-10). Confirmed via a live ZZTestMod probe (research doc 3.16) that an
-- unlockable trait the player hasn't found yet is simply ABSENT from this
-- array, not present at Level=0 - so presence alone means "found," and
-- Level tells you how many points are in it. Archetype/Core traits also
-- live in this same array but are filtered out of MASTER_LIST entirely at
-- build time (match_traits.py), so this only ever needs to look up
-- Unlockable-category entries.
local function readTraitLevels(comp)
    local levels = {}
    local okTraits, traits = pcall(function() return comp.Traits end)
    if not okTraits or traits == nil then
        print("[InventoryTracker] readTraitLevels: comp.Traits unreadable.\n")
        return levels
    end
    local okLen, len = pcall(function() return #traits end)
    if not okLen then
        print("[InventoryTracker] readTraitLevels: #traits unreadable.\n")
        return levels
    end
    for i = 1, len do
        local okEntry, entry = pcall(function() return traits[i] end)
        if okEntry and entry ~= nil then
            local unwrapped = entry
            if type(entry) == "userdata" then
                local okGet, inner = pcall(function() return entry:get() end)
                if okGet and inner ~= nil then unwrapped = inner end
            end
            local okBP, traitBP = pcall(function() return unwrapped.TraitBP end)
            local okLevel, level = pcall(function() return unwrapped.Level end)
            if okBP and traitBP ~= nil and okLevel then
                local okPath, path = pcall(function() return traitBP:GetFullName() end)
                if okPath and path then
                    local assetPath = string.match(path, "(/Game/.+)$")
                    if assetPath then levels[string.lower(assetPath)] = level end
                end
            end
        end
    end
    return levels
end

-- ============================================================================
-- UI - bare-Lua UMG construction, recipe proven via ZZTestMod (research doc
-- 3.17). No existing Blueprint template asset needed for any of this.
-- ============================================================================

local function findClass(path)
    local ok, cls = pcall(function() return StaticFindObject(path) end)
    if ok and cls and cls:IsValid() then return cls end
    print(string.format("[InventoryTracker] findClass FAILED for %s (ok=%s)\n", path, tostring(ok)))
    return nil
end

local function findWidgetBlueprintLibrary()
    local ok, wbl = pcall(function() return StaticFindObject("/Script/UMG.Default__WidgetBlueprintLibrary") end)
    if ok and wbl and wbl:IsValid() then return wbl end
    print(string.format("[InventoryTracker] findWidgetBlueprintLibrary FAILED (ok=%s)\n", tostring(ok)))
    return nil
end

-- Struct write-back pattern (research doc 3.4bb): read into a local, mutate
-- the local's nested fields, assign the WHOLE struct back - in-place
-- mutation of the original reference silently doesn't apply.
local function setTextColor(textBlock, r, g, b)
    pcall(function()
        local color = textBlock.ColorAndOpacity
        color.SpecifiedColor.R = r
        color.SpecifiedColor.G = g
        color.SpecifiedColor.B = b
        color.SpecifiedColor.A = 1.0
        color.ColorUseRule = 0 -- UseColor_Specified
        textBlock.ColorAndOpacity = color
    end)
end

local function wikiUrl(name)
    return "https://remnant2.wiki.gg/wiki/" .. string.gsub(name, " ", "_")
end

-- Panel state. Rebuilt fresh each time it's opened (owned/traitLevels are
-- re-scanned, never cached across opens); only the currently-displayed
-- category persists across an open/close cycle, so reopening returns to
-- where you left off.
local panel = nil
local ownerController = nil
local rowsContainer = nil
local headerText = nil
local currentCategoryIndex = 1
local cachedOwned = {}
local cachedTraitLevels = {}

local function closePanel()
    if panel then
        pcall(function() panel:RemoveFromParent() end)
        panel = nil
    end
    if ownerController then
        local wbl = findWidgetBlueprintLibrary()
        if wbl then
            pcall(function()
                wbl:SetInputMode_GameOnly(ownerController, false)
                ownerController.bShowMouseCursor = false
            end)
        end
        ownerController = nil
    end
    rowsContainer = nil
    headerText = nil
end

local function renderCategory(index)
    if not rowsContainer or not headerText then return end
    local count = #CATEGORY_ORDER
    currentCategoryIndex = ((index - 1) % count) + 1
    local category = CATEGORY_ORDER[currentCategoryIndex]
    local entries = MASTER_LIST_BY_CATEGORY[category] or {}

    pcall(function() rowsContainer:ClearChildren() end)

    local textBlockClass = findClass("/Script/UMG.TextBlock")
    local hBoxClass = findClass("/Script/UMG.HorizontalBox")
    if not textBlockClass or not hBoxClass then return end

    local ownedCount = 0
    for _, item in ipairs(entries) do
        local okRow = pcall(function()
            local hBox = StaticConstructObject(hBoxClass, panel.WidgetTree)
            local nameText = StaticConstructObject(textBlockClass, panel.WidgetTree)
            local urlText = StaticConstructObject(textBlockClass, panel.WidgetTree)

            if category == "Trait" then
                local level = cachedTraitLevels[string.lower(item.classPath)]
                if level ~= nil then
                    ownedCount = ownedCount + 1
                    nameText.Text = FText(string.format("[X] %s - %d/10", item.name, level))
                    setTextColor(nameText, 0.0, 0.45, 0.0)
                    urlText.Text = FText("  " .. wikiUrl(item.name))
                else
                    nameText.Text = FText("[ ] " .. item.name)
                    setTextColor(nameText, 0.6, 0.0, 0.0)
                    local sourceText = item.source and (item.source .. "  -  ") or ""
                    urlText.Text = FText("  " .. sourceText .. wikiUrl(item.name))
                end
            else
                local has = cachedOwned[string.lower(item.classPath)] == true
                if has then ownedCount = ownedCount + 1 end
                nameText.Text = FText(string.format("[%s] %s", has and "X" or " ", item.name))
                setTextColor(nameText, has and 0.0 or 0.6, has and 0.45 or 0.0, 0.0)
                urlText.Text = FText("  " .. wikiUrl(item.name))
            end
            setTextColor(urlText, 0.3, 0.3, 0.3)

            hBox:AddChild(nameText)
            hBox:AddChild(urlText)
            rowsContainer:AddChild(hBox)
        end)
        if not okRow then
            print(string.format("[InventoryTracker] renderCategory: row for '%s' failed to build.\n", item.name))
        end
    end

    -- headerText is already live in the tree by the time this runs (added
    -- and AddToViewport'd before the first renderCategory call, then
    -- updated in place on every category switch after) - a raw .Text
    -- property write on an ALREADY-LIVE widget doesn't reliably trigger
    -- Slate to re-layout (research doc H4/3.4bb: raw writes are only safe
    -- for "plain data," not anything Slate needs to react to; row text
    -- avoids this because it's set BEFORE AddChild, not after). Use the
    -- real SetText() function instead - FText(...)-wrapped, the
    -- already-established-safe way to pass a string into an FText
    -- parameter (research doc 3.4b).
    local okHeaderText, errHeaderText = pcall(function()
        headerText:SetText(FText(string.format(
            "[%d/%d] %s  -  %d/%d owned  -  Page Up/Down: switch category, F8: close",
            currentCategoryIndex, count, category, ownedCount, #entries)))
    end)
    print(string.format("[InventoryTracker] renderCategory(%s): %d rows, header write ok=%s err=%s\n",
        category, #entries, tostring(okHeaderText), tostring(errHeaderText)))
end

local function openPanel()
    local playerController = FindFirstOf("PlayerController")
    if not playerController then
        print("[InventoryTracker] F8: no PlayerController found.\n")
        return
    end
    local pawns = FindAllOf("Character_Master_Player_Base_C")
    local pawn = nil
    if pawns then
        for _, p in ipairs(pawns) do
            local ok, valid = pcall(function() return p:IsValid() end)
            if ok and valid then pawn = p break end
        end
    end
    if not pawn then
        print("[InventoryTracker] F8: no valid pawn - load a save first.\n")
        return
    end

    local inv = findOwnedInventoryComponent(pawn)
    if not inv then
        print("[InventoryTracker] F8: no Inventory component found.\n")
        return
    end
    cachedOwned = readOwnedClassPaths(inv)

    local traitsComp = findTraitsComponent(pawn)
    cachedTraitLevels = traitsComp and readTraitLevels(traitsComp) or {}
    if not traitsComp then
        print("[InventoryTracker] F8: no TraitsComponent found - traits will show as missing.\n")
    end

    local userWidgetClass = findClass("/Script/UMG.UserWidget")
    local widgetTreeClass = findClass("/Script/UMG.WidgetTree")
    local overlayClass = findClass("/Script/UMG.Overlay")
    local borderClass = findClass("/Script/UMG.Border")
    local sizeBoxClass = findClass("/Script/UMG.SizeBox")
    local scrollBoxClass = findClass("/Script/UMG.ScrollBox")
    local vBoxClass = findClass("/Script/UMG.VerticalBox")
    local textBlockClass = findClass("/Script/UMG.TextBlock")
    if not (userWidgetClass and widgetTreeClass and overlayClass and borderClass and sizeBoxClass
            and scrollBoxClass and vBoxClass and textBlockClass) then
        print("[InventoryTracker] F8: missing a required engine class - aborting.\n")
        return
    end

    local okPanel, newPanel = pcall(function() return StaticConstructObject(userWidgetClass, playerController) end)
    if not okPanel or not newPanel or not newPanel:IsValid() then
        print("[InventoryTracker] F8: failed to construct the panel widget.\n")
        return
    end

    local okTree, tree = pcall(function() return StaticConstructObject(widgetTreeClass, newPanel) end)
    if not okTree or not tree or not tree:IsValid() then
        print("[InventoryTracker] F8: failed to construct the panel's WidgetTree.\n")
        return
    end
    pcall(function() newPanel.WidgetTree = tree end)

    -- Overlay (fills the screen, invisible) hosts the actual bounded panel -
    -- AddToViewport's own slot is never reliably writable via Lua, so we
    -- size/align via AddChild's slot instead (research doc 3.17, point 7).
    local okOverlay, overlay = pcall(function() return StaticConstructObject(overlayClass, tree) end)
    local okOuterSizeBox, outerSizeBox = pcall(function() return StaticConstructObject(sizeBoxClass, tree) end)
    local okBorder, border = pcall(function() return StaticConstructObject(borderClass, tree) end)
    local okOuterVBox, outerVBox = pcall(function() return StaticConstructObject(vBoxClass, tree) end)
    local okHeader, header = pcall(function() return StaticConstructObject(textBlockClass, tree) end)
    local okScroll, scrollBox = pcall(function() return StaticConstructObject(scrollBoxClass, tree) end)
    local okRowsVBox, rowsVBox = pcall(function() return StaticConstructObject(vBoxClass, tree) end)
    if not (okOverlay and overlay:IsValid() and okOuterSizeBox and outerSizeBox:IsValid()
            and okBorder and border:IsValid() and okOuterVBox and outerVBox:IsValid()
            and okHeader and header:IsValid() and okScroll and scrollBox:IsValid()
            and okRowsVBox and rowsVBox:IsValid()) then
        print("[InventoryTracker] F8: failed to construct one of the panel's containers.\n")
        return
    end

    -- Full screen, both dimensions (per user request - the fixed 900px
    -- width felt cramped once real data was in it). No WidthOverride/
    -- HeightOverride at all now - both axes are Fill via the overlay
    -- slot's alignment below, same mechanism already proven for height.
    -- outerSizeBox is kept in the tree structurally (harmless, no size
    -- override applied) rather than removed, to avoid touching the nesting
    -- chain that's already proven working.

    pcall(function()
        local color = border.BrushColor
        color.R, color.G, color.B, color.A = 0.95, 0.95, 0.95, 0.95
        border.BrushColor = color
    end)

    setTextColor(header, 0.1, 0.1, 0.1)

    -- The ScrollBox's slot in outerVBox needs Fill sizing so it takes all
    -- remaining vertical space below the header (header stays its natural/
    -- automatic height) - struct write-back on the slot's Size, same
    -- pattern as every other struct property write in this file.
    local okNest, errNest = pcall(function()
        local headerSlotOk, headerSlot = pcall(function() return outerVBox:AddChild(header) end)
        if headerSlotOk and headerSlot then
            -- Explicit Automatic sizing - don't rely on whatever a fresh
            -- VerticalBoxSlot's SizeRule defaults to; guarantees "one
            -- natural text line," not a 50/50 split with the ScrollBox's
            -- Fill slot below. Confirmed necessary and working 2026-07-28.
            pcall(function()
                local size = headerSlot.Size
                size.SizeRule = 0 -- ESlateSizeRule.Automatic
                size.Value = 1
                headerSlot.Size = size
            end)
        end
        local scrollSlotOk, scrollSlot = pcall(function() return outerVBox:AddChild(scrollBox) end)
        if scrollSlotOk and scrollSlot then
            local size = scrollSlot.Size
            size.SizeRule = 1 -- ESlateSizeRule.Fill
            size.Value = 1
            scrollSlot.Size = size
        end
        scrollBox:AddChild(rowsVBox)
        border:AddChild(outerVBox)
        outerSizeBox:AddChild(border)
        overlay:AddChild(outerSizeBox)
        tree.RootWidget = overlay
    end)
    if not okNest then
        print(string.format("[InventoryTracker] F8: failed to nest the panel's widget tree: %s\n", tostring(errNest)))
        return
    end

    -- outerSizeBox's slot (a UOverlaySlot, populated by the AddChild call
    -- above - AddChild-populated slots are reliable, AddToViewport's is
    -- not) - Fill/Fill so the panel covers the whole screen, per user
    -- request.
    pcall(function()
        local slot = outerSizeBox.Slot
        slot:SetHorizontalAlignment(0) -- HAlign_Fill
        slot:SetVerticalAlignment(0)   -- VAlign_Fill
    end)

    local okAdd = pcall(function() newPanel:AddToViewport(0) end)
    if not okAdd then
        print("[InventoryTracker] F8: AddToViewport failed.\n")
        return
    end

    panel = newPanel
    rowsContainer = rowsVBox
    headerText = header

    local wbl = findWidgetBlueprintLibrary()
    if wbl then
        local okMode = pcall(function()
            wbl:SetInputMode_GameAndUIEx(playerController, newPanel, 0, false, false) -- 0 = EMouseLockMode.DoNotLock
            playerController.bShowMouseCursor = true
        end)
        if okMode then ownerController = playerController end
    end

    renderCategory(currentCategoryIndex)
end

RegisterKeyBind(Key.F8, function()
    ExecuteInGameThread(function()
        if panel then
            closePanel()
        else
            openPanel()
        end
    end)
end)

RegisterKeyBind(Key.PAGE_UP, function()
    if not panel then return end
    ExecuteInGameThread(function() renderCategory(currentCategoryIndex - 1) end)
end)

RegisterKeyBind(Key.PAGE_DOWN, function()
    if not panel then return end
    ExecuteInGameThread(function() renderCategory(currentCategoryIndex + 1) end)
end)

print("[InventoryTracker] Ready - press F8 to open the tracker panel.\n")
