print("[InventoryTracker] Loaded and running.\n")

-- InventoryTracker: shows which unique equippable items the player currently
-- has vs. what's missing. Phase 1 (rings + amulets) proved the pipeline;
-- Phase 2 added armor + weapon mods (2026-07-27, research doc 3.12). Weapons,
-- traits, mutators, and consumables are still not covered - those need
-- different ownership logic (see docs/remnant2-modding-research.md 3.10).
--
-- CONFIRMED CEILING (research doc 3.10): the game has no persistent "ever
-- obtained" flag anywhere in native reflection. This mod can only ever
-- reflect CURRENT inventory contents - a sold/dismantled unique will show as
-- missing again. Known, accepted limitation, not a bug.
--
-- Ownership check: scan RemnantPlayerInventoryComponent.Items (a plain
-- TArray<FInventoryItem> property, read directly - no function call) for an
-- entry whose .ItemBP class path matches the master list entry. Deliberately
-- NOT calling HasItem() - it takes a TSoftClassPtr (a struct, not a raw
-- pointer) and crashed the game when called with a raw UClass value
-- (research doc 3.10 hazard). Property reads only, per the risk ladder.
--
-- MASTER LIST: 484 entries across rings/amulets (Phase 1) + armor/weapon mods
-- (Phase 2), built from FModel exports matched against wiki name lists. Full
-- build process, exclusions (BlessedNecklace/FlickerCloak/etc - no wiki
-- match, likely Remnant 1 leftovers), and manual name-fix pairings are in
-- research doc 3.11-3.12. Class paths come from each item's own "Package"
-- field (exact, patch-safe); display names come from the wiki since the game
-- has no static name string anywhere in its data (names are built at runtime
-- via ModifyInspectInfo).
--
-- Data lives in master_list_data.lua, generated by
-- scripts/InventoryTracker/generate_lua.py from dev-data/master_list/*.json
-- (themselves rebuilt by match_rings_amulets.py/match_armor.py/match_mods.py
-- against a fresh dev-data/Exports/ scan) - not hand-maintained here. To add
-- a category or fix a name, edit the Python pipeline and re-run it, don't
-- hand-edit master_list_data.lua.
local MASTER_LIST = require("master_list_data")

local function findOwnedInventoryComponent(pawn)
    local all = FindAllOf("RemnantPlayerInventoryComponent")
    if not all then return nil end
    for _, c in ipairs(all) do
        local ok, owner = pcall(function() return c:GetOuter() end)
        if ok and owner then
            local okSame, same = pcall(function() return owner:GetFullName() == pawn:GetFullName() end)
            if okSame and same then return c end
        end
    end
    return nil
end

-- Returns a set of owned class-path strings (lowercased) read from the live
-- Items array. Built fresh each check - session-lifetime caching can come
-- later once this is proven correct.
local function readOwnedClassPaths(inv)
    local owned = {}
    local okItems, items = pcall(function() return inv.Items end)
    if not okItems or items == nil then
        print("[InventoryTracker] readOwnedClassPaths: inv.Items unreadable.\n")
        return owned
    end
    local okLen, len = pcall(function() return #items end)
    if not okLen then
        print("[InventoryTracker] readOwnedClassPaths: #items unreadable.\n")
        return owned
    end
    for i = 1, len do
        local okEntry, entry = pcall(function() return items[i] end)
        if okEntry and entry ~= nil then
            local unwrapped = entry
            if type(entry) == "userdata" then
                local okGet, inner = pcall(function() return entry:get() end)
                if okGet and inner ~= nil then unwrapped = inner end
            end
            local okClass, itemClass = pcall(function() return unwrapped.ItemBP end)
            if okClass and itemClass ~= nil then
                local okPath, path = pcall(function() return itemClass:GetFullName() end)
                if okPath and path then
                    -- GetFullName() looks like "BlueprintGeneratedClass /Game/.../Ring_X.Ring_X_C";
                    -- keep just the "/Game/..." part to compare against MASTER_LIST classPath.
                    local assetPath = string.match(path, "(/Game/.+)$")
                    if assetPath then owned[string.lower(assetPath)] = true end
                end
            end
        end
    end
    return owned
end

local function findTraitsComponent(pawn)
    local all = FindAllOf("TraitsComponent")
    if not all then return nil end
    for _, c in ipairs(all) do
        local ok, owner = pcall(function() return c:GetOuter() end)
        if ok and owner then
            local okSame, same = pcall(function() return owner:GetFullName() == pawn:GetFullName() end)
            if okSame and same then return c end
        end
    end
    return nil
end

-- Traits work differently from every other category: ownership isn't an
-- inventory scan, it's presence in TraitsComponent.Traits (a plain
-- TArray<FTraitInfo> property - Level is the player's allocated points,
-- 0-10). Confirmed via a live ZZTestMod probe (research doc 3.16) that an
-- unlockable trait the player hasn't found yet is simply ABSENT from this
-- array, not present at Level=0 - so presence alone means "found," and
-- Level tells you how many points are in it. Archetype/Core traits also
-- live in this same array but are filtered out of MASTER_LIST entirely at
-- build time (match_traits.py), so this only ever needs to look up
-- Unlockable-category entries.
local function readTraitLevels(comp)
    local levels = {}
    local okTraits, traits = pcall(function() return comp.Traits end)
    if not okTraits or traits == nil then
        print("[InventoryTracker] readTraitLevels: comp.Traits unreadable.\n")
        return levels
    end
    local okLen, len = pcall(function() return #traits end)
    if not okLen then
        print("[InventoryTracker] readTraitLevels: #traits unreadable.\n")
        return levels
    end
    for i = 1, len do
        local okEntry, entry = pcall(function() return traits[i] end)
        if okEntry and entry ~= nil then
            local unwrapped = entry
            if type(entry) == "userdata" then
                local okGet, inner = pcall(function() return entry:get() end)
                if okGet and inner ~= nil then unwrapped = inner end
            end
            local okBP, traitBP = pcall(function() return unwrapped.TraitBP end)
            local okLevel, level = pcall(function() return unwrapped.Level end)
            if okBP and traitBP ~= nil and okLevel then
                local okPath, path = pcall(function() return traitBP:GetFullName() end)
                if okPath and path then
                    local assetPath = string.match(path, "(/Game/.+)$")
                    if assetPath then levels[string.lower(assetPath)] = level end
                end
            end
        end
    end
    return levels
end

RegisterKeyBind(Key.F8, function()
    print("[InventoryTracker] F8 pressed - checking inventory.\n")
    ExecuteInGameThread(function()
        local pawns = FindAllOf("Character_Master_Player_Base_C")
        local pawn = nil
        if pawns then
            for _, p in ipairs(pawns) do
                local ok, valid = pcall(function() return p:IsValid() end)
                if ok and valid then pawn = p break end
            end
        end
        if not pawn then
            print("[InventoryTracker] F8: no valid pawn - load a save first.\n")
            return
        end

        local inv = findOwnedInventoryComponent(pawn)
        if not inv then
            print("[InventoryTracker] F8: no Inventory component found.\n")
            return
        end

        local owned = readOwnedClassPaths(inv)

        local traitsComp = findTraitsComponent(pawn)
        local traitLevels = traitsComp and readTraitLevels(traitsComp) or {}
        if not traitsComp then
            print("[InventoryTracker] F8: no TraitsComponent found - traits will show as missing.\n")
        end

        local ownedCount, missingCount = 0, 0
        for _, item in ipairs(MASTER_LIST) do
            if item.category == "Trait" then
                local level = traitLevels[string.lower(item.classPath)]
                if level ~= nil then
                    ownedCount = ownedCount + 1
                    print(string.format("[InventoryTracker]   [X] (Trait) %s - %d/10\n", item.name, level))
                else
                    missingCount = missingCount + 1
                    local sourceText = item.source and (" - " .. item.source) or ""
                    print(string.format("[InventoryTracker]   [ ] (Trait) %s%s\n", item.name, sourceText))
                end
            else
                local has = owned[string.lower(item.classPath)] == true
                if has then ownedCount = ownedCount + 1 else missingCount = missingCount + 1 end
                print(string.format("[InventoryTracker]   [%s] (%s) %s\n", has and "X" or " ", item.category, item.name))
            end
        end
        print(string.format("[InventoryTracker] F8: %d owned, %d missing (of %d total).\n",
            ownedCount, missingCount, #MASTER_LIST))
    end)
end)

print("[InventoryTracker] Ready - press F8 to check inventory.\n")
